version: "3.8"
services:
  postgres-db:
    container_name: guitar-final2
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: guitaruser
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: Guitar-Project2
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5436:5432"

volumes:
  postgresql_data:
    driver: local