CREATE TABLE interests_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    interest_type VARCHAR(255),
    CONSTRAINT pk_interestsentity PRIMARY KEY (id)
);

ALTER TABLE guitarprojectdata
    ADD interests_id BIGINT;

ALTER TABLE guitarprojectdata
    ADD CONSTRAINT FK_GUITARPROJECTDATA_ON_INTERESTS FOREIGN KEY (interests_id) REFERENCES interests_entity (id);